### ISSUE TITLE
Doesn't covert punctuation and translation isn't quite right

### ISSUE THREAD

**Issue by ayroblu** [vbarzokas/greek-utils#3]
Hey love your work, would like the punctation to change too though:

```javascript
const greekUtils = require('greek-utils')
const text = greekUtils.toGreeklish('Παρακαλώ;')
console.log(text)
```

Expected: parakaló?
Actual: parakalw;

I had a quick search for this as reference: https://billmounce.com/greekalphabet/greek-punctuation-syllabification as well as google translate

**Comment by vbarzokas** [comment]
Hi ayroblu, thanks for your feedback.
 
I am going to add the puncuation mapping of `;` to `?` to the `.toGreeklish` method.

Regarding the translation of `ώ` to `ó` and probably other characters (eg. `θ` το `8`), I followed this pattern which is to convert the latin character to the one that is visually similar to the greek one by keeping the orthography of  the word, so a native greek (or generally someone who can read greek) can read it seamleslly like it was spelled with greek characters.
The term `greeklish` is properly covered in this article 
https://en.wikipedia.org/wiki/Greeklish

What you suggest is the phonetic traslate of the greek letters, or as described in this artice the "romanization" of them
https://en.wikipedia.org/wiki/Romanization_of_Greek
Which is something I believe is very useful and I am going to add it, but in a new separate method because it is a different concept.

**Comment by ayroblu** [comment]
Okay cool, thanks for the update!
